name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        cd ts
        npm ci
    - name: Test
      run: |
        cd ts
        npm test
      env:
        CI: true
